// This file was generated by generateIconTypesPlugin
/* eslint-disable */ 

export const iconsList: Array<{ folder: string; icons: string[] }> = [
	{
		"folder": "actions",
		"icons": [
			"add",
			"close-panel",
			"close",
			"copy",
			"download",
			"edit",
			"external",
			"menu",
			"more",
			"open-in-full",
			"open-panel",
			"pause",
			"play",
			"remove",
			"search",
			"subnav"
		]
	},
	{
		"folder": "arrows",
		"icons": [
			"arrow_down",
			"arrow_left",
			"arrow_right",
			"arrow_up",
			"back",
			"tick_m_down",
			"tick_m_left",
			"tick_m_right",
			"tick_m_up",
			"tick_s_down",
			"tick_s_up"
		]
	},
	{
		"folder": "checked",
		"icons": [
			"check",
			"checkbox-checked",
			"checkbox-empty",
			"checkbox-Indeterminate",
			"done-all",
			"radio-selected",
			"radio-unselected"
		]
	},
	{
		"folder": "entrance",
		"icons": [
			"logout",
			"user"
		]
	},
	{
		"folder": "game-rating",
		"icons": [
			"age12",
			"alcohol-and-smoking",
			"drugs",
			"fear",
			"payment",
			"sex",
			"swear",
			"violence"
		]
	},
	{
		"folder": "games",
		"icons": [
			"mk-logo",
			"rq-logo",
			"superball-logo"
		]
	},
	{
		"folder": "information",
		"icons": [
			"asterisk",
			"attention-outline",
			"attention",
			"calendar-outline",
			"calendar",
			"computer",
			"document",
			"email-fill",
			"email-outline",
			"email",
			"language",
			"link",
			"notification",
			"password",
			"pin",
			"settings",
			"storage",
			"support-outline",
			"support",
			"synchronization",
			"update",
			"visibility-off",
			"visibility"
		]
	},
	{
		"folder": "logo",
		"icons": [
			"apple",
			"base-icon",
			"base-logo",
			"discord-brand",
			"discord",
			"facebook-brand",
			"facebook",
			"google-brand",
			"google",
			"instagram",
			"lesta-brand-dark",
			"lesta-brand-light",
			"lesta",
			"ok-brand",
			"ok",
			"reddit-brand",
			"reddit",
			"rutube-brand",
			"rutube",
			"steam-brand",
			"steam-white",
			"steam",
			"telegram-brand",
			"telegram",
			"tiktok-brand",
			"tiktok",
			"twitch-brand",
			"twitch",
			"vk-brand",
			"vk",
			"windows",
			"x-brand",
			"x",
			"yandex-brand",
			"yandex",
			"youtube-brand",
			"youtube"
		]
	},
	{
		"folder": "markers",
		"icons": [
			"circle",
			"marker",
			"outlined-circle",
			"pagination_m",
			"pagination_s",
			"slide"
		]
	},
	{
		"folder": "payment",
		"icons": [
			"belkart-brand",
			"belkart-internet-brand",
			"belkart-internet",
			"belkart",
			"bepaid-brand",
			"bepaid",
			"g-pay-brand",
			"g-pay",
			"mastercard-brand",
			"mastercard-id-brand",
			"mastercard-id-gray",
			"mastercard-id-white",
			"mastercard",
			"visa-brand",
			"visa-secure-brand",
			"visa-secure-gray",
			"visa-secure-white",
			"visa"
		]
	},
	{
		"folder": "shop",
		"icons": [
			"bag",
			"card",
			"coin",
			"favorite-outline",
			"favorite",
			"gift-outline",
			"gift",
			"promocode-outline",
			"promocode",
			"star-outline",
			"star"
		]
	},
	{
		"folder": "sorting-and-filter",
		"icons": [
			"filter-outline",
			"filter",
			"sort-down",
			"sort-up",
			"sort"
		]
	},
	{
		"folder": "root",
		"icons": [
			"spinner"
		]
	},
	{
		"folder": "window",
		"icons": [
			"collapse",
			"expand",
			"turn"
		]
	}
];
