import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { styleText } from 'node:util';
import type { Plugin } from 'vite';

interface GenerateBarrelPluginArgs {
	srcDir: string;
	outputFile: string;
	exclude?: string[];
}

export function generateBarrel(srcDirectory: string, outputPath: string, exclude: string[] = []): void {
	console.log('🔧 Generating barrel index.ts...');

	const exports = collectExports(srcDirectory, srcDirectory, exclude);

	if (exports.length === 0) {
		console.log('No exports found, skipping generation.');
		return;
	}

	const content = [
		'// This file was generated by generateBarrelPlugin',
		'',
		...exports.map((p) => `export * from '${p}';`),
		'',
	].join('\n');

	writeFileSync(outputPath, content, 'utf8');

	console.log(styleText(['green'], '✅ Barrel index.ts generated successfully!'));
	console.log(`Output: ${outputPath}`);
}

export function generateBarrelPlugin(args: GenerateBarrelPluginArgs): Plugin {
	const { srcDir, outputFile, exclude = [] } = args;

	return {
		name: 'generate-barrel',
		configResolved(config) {
			generateBarrel(
				resolve(config.root, srcDir),
				resolve(config.root, outputFile),
				exclude,
			);
		},
	};
}

function collectExports(srcDir: string, currentDir: string, exclude: string[]): string[] {
	const entries = readdirSync(currentDir, { withFileTypes: true });
	const results: string[] = [];

	for (const entry of entries) {
		if (!entry.isDirectory()) continue;

		const entryPath = join(currentDir, entry.name);
		const relativePath = './' + relative(srcDir, entryPath).replace(/\\/g, '/');

		if (exclude.some((ex) => relativePath.startsWith(ex) || relativePath === ex)) {
			continue;
		}

		const indexPath = join(entryPath, 'index.ts');

		if (existsSync(indexPath)) {
			results.push(relativePath);
		} else {
			results.push(...collectExports(srcDir, entryPath, exclude));
		}
	}

	return results;
}
