import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { styleText } from 'node:util';
import type { Plugin } from 'vite';

import { collectIcons, type IconFolder } from './collectIcons';

interface GenerateIconTypesPluginArgs {
	iconDir: string;
	outputDir: string;
}

export function generateIcons(iconsDirectory: string, outputPath: string): void {
	const list = collectIcons(iconsDirectory);

	if (list.length === 0) {
		console.log('No icons found, skipping generation.');
		return;
	}

	generateIconsType(list, outputPath);
	generateIconsStructure(list, outputPath);
}

export function generateIconTypesPlugin(args: GenerateIconTypesPluginArgs): Plugin {
	const { iconDir, outputDir } = args;

	return {
		name: 'generate-icon-types',
		configResolved(config) {
			generateIcons(join(config.root, iconDir), join(config.root, outputDir));
		},
	};
}

function generateIconsType(iconsArray: IconFolder[], outputPath: string): void {
	console.time('Done in');
	console.log('🔧 Generating Icons type...');

	const filePath = resolve(outputPath, 'icons.types.ts');
	let fileContent = getFileContentPrefix();

	fileContent += 'export type Icons = \n';

	for (const { folder: category, icons } of iconsArray) {
		const names = icons.map((icon) => `'${icon}'`).join(' | ');

		if (category === 'root' || !category) {
			fileContent += `   | { category?: never; name: ${names} }\n`;
		} else {
			fileContent += `   | { category: '${category}'; name: ${names} }\n`;
		}
	}

	fileContent = fileContent.trim() + ';\n\n';
	writeFileSync(filePath, fileContent, 'utf8');

	console.log(styleText(['green'], '✅ Icon types generated successfully!'));
	console.log(`Output: ${filePath}`);
	console.timeEnd('Done in');
	console.log('');
}

function generateIconsStructure(iconsArray: IconFolder[], outputPath: string): void {
	console.time('Done in');
	console.log('🔧 Generating Icons list...');

	const filePath = resolve(outputPath, '_stories/iconsList.ts');
	mkdirSync(dirname(filePath), { recursive: true });

	let fileContent = getFileContentPrefix();

	fileContent += `export const iconsList: Array<{ folder: string; icons: string[] }> = ${JSON.stringify(iconsArray, null, '\t')};\n`;
	writeFileSync(filePath, fileContent, 'utf8');

	console.log(styleText(['green'], '✅ Icon list generated successfully!'));
	console.log(`Output: ${filePath}`);
	console.timeEnd('Done in');
	console.log('');
}

function getFileContentPrefix(): string {
	return '// This file was generated by generateIconTypesPlugin\n\n';
}
