// This file was generated by generateIconTypesPlugin

export type Icons = 
   | { category?: never; name: 'spinner' }
   | { category: 'actions'; name: 'add' | 'close-panel' | 'close' | 'copy' | 'download' | 'edit' | 'external' | 'menu' | 'more' | 'open-in-full' | 'open-panel' | 'pause' | 'play' | 'remove' | 'search' | 'subnav' }
   | { category: 'arrows'; name: 'arrow_down' | 'arrow_left' | 'arrow_right' | 'arrow_up' | 'back' | 'tick_m_down' | 'tick_m_left' | 'tick_m_right' | 'tick_m_up' | 'tick_s_down' | 'tick_s_up' }
   | { category: 'checked'; name: 'check' | 'checkbox-checked' | 'checkbox-empty' | 'checkbox-Indeterminate' | 'done-all' | 'radio-selected' | 'radio-unselected' }
   | { category: 'entrance'; name: 'logout' | 'user' }
   | { category: 'information'; name: 'asterisk' | 'attention-outline' | 'attention' | 'calendar-outline' | 'calendar' | 'computer' | 'document' | 'email-fill' | 'email-outline' | 'email' | 'language' | 'link' | 'notification' | 'password' | 'pin' | 'settings' | 'storage' | 'support-outline' | 'support' | 'synchronization' | 'update' | 'visibility-off' | 'visibility' }
   | { category: 'logo'; name: 'apple' | 'discord-brand' | 'discord' | 'email' | 'facebook-brand' | 'facebook' | 'github' | 'google-brand' | 'google' | 'instagram' | 'ok-brand' | 'ok' | 'reddit-brand' | 'reddit' | 'rutube-brand' | 'rutube' | 'steam-brand' | 'steam-white' | 'steam' | 'telegram-brand' | 'telegram' | 'tiktok-brand' | 'tiktok' | 'twitch-brand' | 'twitch' | 'vk-brand' | 'vk' | 'windows' | 'x-brand' | 'x' | 'yandex-brand' | 'yandex' | 'youtube-brand' | 'youtube' }
   | { category: 'markers'; name: 'circle' | 'marker' | 'outlined-circle' | 'pagination_m' | 'pagination_s' | 'slide' }
   | { category: 'shop'; name: 'bag' | 'card' | 'coin' | 'favorite-outline' | 'favorite' | 'gift-outline' | 'gift' | 'promocode-outline' | 'promocode' | 'star-outline' | 'star' }
   | { category: 'sorting-and-filter'; name: 'filter-outline' | 'filter' | 'sort-down' | 'sort-up' | 'sort' };

