// This file was generated by generateIconTypesPlugin
/* eslint-disable */

export type Icons =
	| { category?: never; name: 'spinner' }
	| { category: 'actions'; name: 'add' | 'copy' }
	| { category: 'entrance'; name: 'user' };
