// This file was generated by generateIconTypesPlugin
/* eslint-disable */

export const iconsList: Array<{ folder: string; icons: string[] }> = [
	{
		folder: 'root',
		icons: ['spinner'],
	},
	{
		folder: 'actions',
		icons: ['add', 'copy'],
	},
	{
		folder: 'entrance',
		icons: ['user'],
	},
];
