// This file was generated by generateIconTypesPlugin
/* eslint-disable */ 

export type Icons = 
   | { category: 'actions'; name: 'add' | 'close-panel' | 'close' | 'copy' | 'download' | 'edit' | 'external' | 'menu' | 'more' | 'open-in-full' | 'open-panel' | 'pause' | 'play' | 'remove' | 'search' | 'subnav' }
   | { category: 'arrows'; name: 'arrow_down' | 'arrow_left' | 'arrow_right' | 'arrow_up' | 'back' | 'tick_m_down' | 'tick_m_left' | 'tick_m_right' | 'tick_m_up' | 'tick_s_down' | 'tick_s_up' }
   | { category: 'checked'; name: 'check' | 'checkbox-checked' | 'checkbox-empty' | 'checkbox-Indeterminate' | 'done-all' | 'radio-selected' | 'radio-unselected' }
   | { category: 'entrance'; name: 'logout' | 'user' }
   | { category: 'game-rating'; name: 'age12' | 'alcohol-and-smoking' | 'drugs' | 'fear' | 'payment' | 'sex' | 'swear' | 'violence' }
   | { category: 'games'; name: 'mk-logo' | 'rq-logo' | 'superball-logo' }
   | { category: 'information'; name: 'asterisk' | 'attention-outline' | 'attention' | 'calendar-outline' | 'calendar' | 'computer' | 'document' | 'email-fill' | 'email-outline' | 'email' | 'language' | 'link' | 'notification' | 'password' | 'pin' | 'settings' | 'storage' | 'support-outline' | 'support' | 'synchronization' | 'update' | 'visibility-off' | 'visibility' }
   | { category: 'logo'; name: 'apple' | 'base-icon' | 'base-logo' | 'discord-brand' | 'discord' | 'facebook-brand' | 'facebook' | 'google-brand' | 'google' | 'instagram' | 'lesta-brand-dark' | 'lesta-brand-light' | 'lesta' | 'ok-brand' | 'ok' | 'reddit-brand' | 'reddit' | 'rutube-brand' | 'rutube' | 'steam-brand' | 'steam-white' | 'steam' | 'telegram-brand' | 'telegram' | 'tiktok-brand' | 'tiktok' | 'twitch-brand' | 'twitch' | 'vk-brand' | 'vk' | 'windows' | 'x-brand' | 'x' | 'yandex-brand' | 'yandex' | 'youtube-brand' | 'youtube' }
   | { category: 'markers'; name: 'circle' | 'marker' | 'outlined-circle' | 'pagination_m' | 'pagination_s' | 'slide' }
   | { category: 'payment'; name: 'belkart-brand' | 'belkart-internet-brand' | 'belkart-internet' | 'belkart' | 'bepaid-brand' | 'bepaid' | 'g-pay-brand' | 'g-pay' | 'mastercard-brand' | 'mastercard-id-brand' | 'mastercard-id-gray' | 'mastercard-id-white' | 'mastercard' | 'visa-brand' | 'visa-secure-brand' | 'visa-secure-gray' | 'visa-secure-white' | 'visa' }
   | { category: 'shop'; name: 'bag' | 'card' | 'coin' | 'favorite-outline' | 'favorite' | 'gift-outline' | 'gift' | 'promocode-outline' | 'promocode' | 'star-outline' | 'star' }
   | { category: 'sorting-and-filter'; name: 'filter-outline' | 'filter' | 'sort-down' | 'sort-up' | 'sort' }
   | { category?: never; name: 'spinner' }
   | { category: 'window'; name: 'collapse' | 'expand' | 'turn' };

