import { writeFileSync } from 'fs';
import { join, resolve } from 'path';

import { styleText } from 'node:util';

import { collectIcons } from './collectIcons.mjs';

export function generateIconTypesPlugin(args) {
	const {
		iconDir,
		outputDir
	} = args || {};

	if (!iconDir || !outputDir) {
		throw new Error('"iconDir" and "outputDir" are required parameters!');
	}

	// eslint-disable-next-line sonarjs/no-invariant-returns
	function applyToEnvironment({ config }) {
		const iconsDirectory = join(config.root, iconDir);

		const list = collectIcons(iconsDirectory);

		if (!list || list.length === 0) {
			console.timeEnd('Done in');
			return true;
		}

		const OUTPUT_PATH = join(config.root, outputDir);
		generateIconsType(list, OUTPUT_PATH);
		generateIconsStructure(list, OUTPUT_PATH);

		return true;
	}

	return {
		name: 'generate-icon-types',
		applyToEnvironment,
	};
}

function generateIconsType(iconsArray, outputPath) {
	console.time('Done in');
	console.log('🔧 Generating Icons type...');

	const filePath = resolve(outputPath, 'icons.types.ts');
	let fileContent = getFileContentPrefix();

	fileContent += 'export type Icons = \n';

	iconsArray.forEach((folder) => {
		const { folder: category, icons } = folder;

		if (category === 'root' || !category) {
			fileContent += `   | { category?: never; name: ${icons.map((icon) => `'${icon}'`).join(' | ')} }\n`;
		} else {
			fileContent += `   | { category: '${category}'; name: ${icons.map((icon) => `'${icon}'`).join(' | ')} }\n`;
		}
	});

	fileContent = fileContent.trim() + ';\n\n';
	writeFileSync(filePath, fileContent, 'utf8');

	console.log(styleText(['green'], `✅ Icon types generated successfully!`));
	console.log(`Output: ${filePath}`);
	console.timeEnd('Done in');
	console.log('\n');
}

function generateIconsStructure(iconsArray, outputPath) {
	console.time('Done in');
	console.log('🔧 Generating Icons list...');

	const filePath = resolve(outputPath, '_stories/iconsList.ts');
	let fileContent = getFileContentPrefix();

	fileContent += `export const iconsList: Array<{ folder: string; icons: string[] }> = ${JSON.stringify(iconsArray, null, '\t')};\n`;
	writeFileSync(filePath, fileContent, 'utf8');

	console.log(styleText(['green'], `✅ Icon list generated successfully!`));
	console.log(`Output: ${filePath}`);
	console.timeEnd('Done in');
	console.log('\n');
}

function getFileContentPrefix() {
	return '// This file was generated by generateIconTypesPlugin\n' + '/* eslint-disable */ \n\n'
}