name: TEST

on:
  push:
    branches: [ "feature/github-actions" ]
  pull_request:
    branches: [ "feature/github-actions" ]

jobs:

  our-first-job:

    runs-on: ubuntu-latest

    steps:
      - name: Run console log
        run: echo "Hello GitHub Actions!"
